# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'yaml'

Vagrant.configure(2) do |config|

  Dir.glob('machines/*.yaml') do |machine_file|
    machine_config = YAML.load_file(machine_file)
    name = File.basename(machine_file, ".yaml")
    config.vm.define name do |srv|
        srv.vm.box = machine_config["box"]
        srv.vm.network "private_network", type: "dhcp"
        srv.vm.synced_folder '.', '/vagrant', disabled: true
        srv.ssh.username = machine_config["username"]
        srv.ssh.password = machine_config["password"]
        srv.ssh.private_key_path = machine_config["private_key_path"]
        srv.vm.provider "virtualbox" do |v|
           v.memory = machine_config["memory"]
           v.cpus = machine_config["cpus"]
           v.customize ["modifyvm", :id, "--nictype1", "virtio"]
        end
    end
  end

end